config/routes.rb
Rails.application.routes.draw do
  resources :artists
  # get 'albums/artist/:id' => 'albums#index', :as => :artist_albums
  # get 'albums/artist/:id/new' => 'albums#new', :as => :album_artist_new

  resources :albums
  resources :tracks

  root to: 'artists#index'
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  has_one_attached :cover_art
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, :bio, presence: { 
    message: -> (object, data) do
      "#{data[:attribute]} field is required"
    end
  }
  validates :name, uniqueness: { 
    message: -> (object, data) do
      "#{data[:attribute]} has already been taken"
    end
  }

  has_one_attached :avatar
  has_one_attached :cover_art

  def to_param
    name.parameterize(preserve_case: true)
  end
end

app/models/track.rb
class Track < ApplicationRecord
  validates :name, :url, :credits, presence: { 
    message: -> (object, data) do
      "#{data[:attribute]} field is required"
    end
  }
  validates :name, length: {
    maximum: 50
  }

  has_one_attached :url
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:edit, :destroy, :update]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to albums_path, notice: "#{params[:album][:name]} album has been successfully addded."
    else
      render :new, error: "Something went wrong. Please try again!"
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path, notice: "#{params[:album][:name]} album has been successfully updated."
    else
      render :edit, error: "Something went wrong. Please try again!"
    end
  end

  def destroy
    @album.destroy

    redirect_to albums_path, notice: "Track has been deleted successfully."
  end

  private
  
  def album_params
    is_released = false

    if params[:album][:released] == "Yes"
      is_released = true
      params[:album][:released_at] = Time.now
    end

    params[:album][:released] = is_released
    params.required(:album).permit(:name, :kind, :cover_art, :released, :released_at)
  end

  def set_album
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :destroy, :update]

  def index
    @artists = Artist.all
  end
  
  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path, notice: "#{params[:artist][:name]} artist has been successfully addded."
    else
      render :new, error: "Something went wrong. Please try again!"
    end
  end

  def edit
  end

  def show
    @albums = Album.all
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path, notice: "#{params[:artist][:name]} artist has been successfully updated."
    else
      render :edit, error: "Something went wrong. Please try again!"
    end
  end

  def destroy
    @artist.destroy

    redirect_to artists_path, notice: "An artist has been deleted successfully."
  end

  private
  
  def artist_params
    params[:artist][:slug] = params[:artist][:name].gsub(/_/, '-').parameterize(preserve_case: true)
    params.required(:artist).permit(:name, :bio, :avatar, :cover_art, :slug, :formed_at)
  end

  def set_artist
    @artist = params[:id].match(/^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/) ?  Artist.friendly.find(params[:id]) : Artist.find(params[:id])
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:edit, :destroy, :update]
  
  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new(:available => "No")
  end
  
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to tracks_path, notice: "#{params[:track][:name]} track has been successfully addded."
    else
      render :new, error: 'Something went wrong. Please try again!'
    end
  end

  def edit
  end

  def update
    if @track.update(track_params)
      redirect_to tracks_path, notice: "#{params[:track][:name]} track has been successfully updated."
    else
      render :edit, error: 'Something went wrong. Please try again!'
    end
  end

  def destroy
    @track.destroy

    redirect_to tracks_path, notice: "Track has been deleted successfully."
  end

  private
  
  def track_params
    params.required(:track).permit(:name, :url, :credits, :available)
  end

  def set_track
    @track = Track.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_form.html.haml
= form_with model: @album, class: 'w-full' do |f|
  %div{ class: 'grid grid-cols-2 gap-6 mb-6' }
    %div
      = image_tag asset_path('album_background.jpg'), class: 'h-96 w-full object-cover rounded mb-4', id: 'cover_photo_preview'
      %div{ class: 'flex flex-col gap-2' }
        = f.label :cover_art
        = f.file_field :cover_art, accept:'image/*'

    %div{ class: 'flex flex-col gap-4' }

      %div{ class: 'w-full' }
        = f.text_field :name, class: "#{f.object.errors[:name].present? ? 'border-red-500 border' : 'border-gray-500 border'} rounded p-2 w-full", placeholder: 'Name'
        - if f.object.errors[:name].present?
          %span{ class: 'text-red-500' }= f.object.errors[:name].to_sentence

      %div{ class: 'w-full flex flex-col gap-2' }
        = f.label :kind
        = f.select :kind, ["Extended Play", "Long Play", "Single Play"], style: 'padding: 20px'
      
      %div{ class: 'flex'}
        %div{ class: 'flex-1 gap-2' }
          %h1 Released
          %div{ class: 'flex items-center h-full w-1/2' }
            %div{ class: 'flex-1' }
              = f.radio_button :released, "Yes", :checked => (@album.released == true)
              = f.label :yes
            %div{ class: 'flex-1' }
              = f.radio_button :released, "No", :checked => (@album.released == false)
              = f.label :no

  %div{ class: 'w-full flex mt-2' }
    = f.submit class: 'px-4 py-2 w-40 bg-indigo-800 text-white hover:bg-indigo-700 rounded cursor-pointer'

:javascript
  function showImage (src, target) {
    var fileReader = new FileReader()
    fileReader.onload = function (e) { 
      target.src = this.result
    }
    src.addEventListener("change", function () {
      fileReader.readAsDataURL(src.files[0])
    })
  }

  var albumSrc = document.getElementById("album_cover_art")
  var albumTarget = document.getElementById("cover_photo_preview")
  showImage(albumSrc, albumTarget)

app/views/albums/edit.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2 pb-12'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold py-12' }
          ALBUM >
          = @album.name
        %div{ class: 'py-12 flex gap-4' }
          =link_to albums_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            < Go back
      
      = render 'form'
      

app/views/albums/index.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-3/4 px-20'}
      %div{ class: 'relative h-2/5 '}
        = image_tag asset_path('all_time_low_2021.jpg'), class: 'h-full w-full object-cover'
        %div{ class: 'rounded-full h-48 w-48 flex items-center justify-center bg-gray-200 p-1 absolute -bottom-24', style: 'left: 42%' }
          = image_tag asset_path('default_avatar.png'), class: 'h-full w-full object-cover rounded-full'
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-4xl font-bold uppercase pt-32 pb-12' }
          Albums
        %div{ class: 'pt-32 pb-12 flex gap-4' }
          =link_to artists_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            Artists
          %h1{ class: 'text-gray-400 flex items-center '} /
          =link_to :new_album, class: 'flex items-center text-xl font-bold text-indigo-800' do
            New Album

      %div{ class: 'grid grid-cols-4 w-full gap-6' }
        - @albums.each do |album|
          %div{ class: 'border shadow-lg flex flex-col flex items-center' }
            - if album.cover_art.attached?
              = image_tag album.cover_art, class: 'h-48 w-full object-cover'
            - else
              = image_tag asset_path('album_background.jpg'), class: 'h-48 w-full object-cover'
            %div{ class: 'p-2 flex flex-col w-full' }
              %h1{ class: 'font-bold text-base uppercase my-4 text-center' }
                = album.name
              -# %div{ class: 'flex' }
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } Released
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } 11-20-2021
              -# %div{ class: 'flex' }
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } Length
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } 1 hr and 2 mins
              -# %div{ class: 'flex' }
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } Tracks
              -#   %label{ class: 'text-sm text-gray-800 flex-1' } 21
              %div{ class: 'flex justify-between w-full text-gray-700 border-t p-4 bg-gray-100' }
                =link_to tracks_path, class: 'font-bold hover:underline' do
                  Tracks
                =link_to edit_album_path(album.id), class: 'font-bold hover:underline' do
                  Edit
                =link_to album_path(album.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'font-bold hover:underline' do
                  Delete

app/views/albums/new.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2 pb-12'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold uppercase py-12' }
          Add new album
        %div{ class: 'py-12 flex gap-4' }
          =link_to albums_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            < Go back
      
      = render 'form'
      

app/views/artists/_form.html.haml
= form_with model: @artist, class: 'w-full bg-gray-50 pb-12' do |f|
  %div{ class: 'relative h-2/5 mb-32 rounded'}
    - if @artist.cover_art.attached?
      = image_tag @artist.cover_art, class: 'h-96 w-full object-cover rounded', id: 'cover_art_preview'
    - else
      = image_tag asset_path('default_cover_photo.png'), class: 'h-96 w-full object-cover rounded', id: 'cover_art_preview'
    %div{ class: 'rounded-full h-48 w-48 flex items-center justify-center bg-gray-200 p-1 absolute -bottom-24', style: 'left: 42%' }
      - if @artist.avatar.attached?
        = image_tag @artist.avatar, class: 'h-full w-full object-cover rounded-full rounded', id: 'avatar_preview'
      - else
        = image_tag asset_path('default_avatar.png'), class: 'h-full w-full object-cover rounded-full rounded', id: 'avatar_preview'
  %div{ class: 'grid grid-cols-2 gap-6 mb-6' }
    %div{ class: 'flex flex-col gap-2' }
      = f.label :cover_art
      = f.file_field :cover_art, accept:'image/*'
    %div{ class: 'flex flex-col gap-2' }
      = f.label :avatar
      = f.file_field :avatar, accept:'image/*'

    %div{ class: 'w-full' }
      = f.text_field :name, class: "#{f.object.errors[:name].present? ? 'border-red-500 border' : 'border-gray-500 border'} p-2 w-full rounded", placeholder: 'Name'
      - if f.object.errors[:name].present?
        %span{ class: 'text-red-500' }= f.object.errors[:name].to_sentence

    %div{ class: 'w-full' }
      = f.date_field :formed_at, class: "#{f.object.errors[:formed_at].present? ? 'border-red-500 border' : 'border-gray-500 border'} p-2 w-full rounded", placeholder: 'Name'
      - if f.object.errors[:formed_at].present?
        %span{ class: 'text-red-500' }= f.object.errors[:formed_at].to_sentence
  
  = f.text_area :bio, class: "#{f.object.errors[:bio].present? ? 'border-red-500 border' : 'border-gray-500 border'} p-2 w-full rounded", rows: 5, placeholder: 'Write something for the bio...'
  - if f.object.errors[:bio].present?
    %span{ class: 'text-red-500' }= f.object.errors[:bio].to_sentence

  %div{ class: 'w-full flex justify-end mt-4' }
    = f.submit class: 'px-4 py-2 w-40 bg-indigo-800 text-white hover:bg-indigo-700 cursor-pointer rounded'

:javascript
  function showImage (src, target) {
    var fileReader = new FileReader()
    fileReader.onload = function (e) { 
      target.src = this.result
    }
    src.addEventListener("change", function () {
      fileReader.readAsDataURL(src.files[0])
    })
  }

  var coverArtSrc = document.getElementById("artist_cover_art")
  var coverArtTarget = document.getElementById("cover_art_preview")
  showImage(coverArtSrc, coverArtTarget)

  var avatarSrc = document.getElementById("artist_avatar")
  var avatarTarget = document.getElementById("avatar_preview")
  showImage(avatarSrc, avatarTarget)
  

app/views/artists/edit.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold py-12' }
          ARTIST >
          = @artist.name
        %div{ class: 'py-12 flex gap-4' }
          =link_to artists_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            < Go back
      
      = render 'form'
      

app/views/artists/index.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-3/4 px-20'}
      %h1{ class: 'text-4xl font-bold uppercase py-12' }
        ARTISTS
        
      %div{ class: 'grid grid-cols-3 w-full gap-6' }
      
        - @artists.each do |artist|
          %div{ class: 'border shadow-lg flex flex-col flex items-center' }
            - if artist.avatar.attached?
              = image_tag artist.avatar, class: 'h-96 w-full object-cover'
            - else
              = image_tag asset_path('default_avatar.png'), class: 'h-96 w-full object-cover'
            %div{ class: 'bg-indigo-800 py-4 px-6 w-3/5 -mt-7 text-white text-center' }
              =link_to artist_path(artist), class: 'font-bold hover:underline' do
                = artist.name.truncate(25)
            %div{ class: 'p-6 w-full' }
              %div{ class: 'flex justify-between w-full text-gray-700' }
                =link_to albums_path, class: 'font-bold hover:underline' do
                  Albums
                =link_to edit_artist_path(artist.id), class: 'font-bold hover:underline' do
                  Edit
                =link_to artist_path(artist.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'font-bold hover:underline' do
                  Delete

      %div{ class: 'w-full py-20' }
        - if @artists.empty?
          %h1{ class: 'w-full text-center font-semibold text-4xl text-gray-400 border-t-2 py-10' } No data available
        %div{ class: 'w-full grid grid-cols-2' }
          %img{ src: asset_path('girl_music.webp') }
          %div{ class: 'px-6 flex flex-col justify-center' }
            %h1{ class: 'font-bold text-4xl uppercase mb-6' } Add New Artist
            %p{ class: 'text-gray-600 mb-7 leading-6' } The quick brown fox jump over the lazy dog near the bank of the river. The quick brown fox jump over the lazy dog near the bank of the river. The quick brown fox jump over the lazy dog near the bank of the river.
            =link_to :new_artist, class: 'text-center bg-transparent hover:bg-indigo-800 hover:text-white hover:border-0 text-indigo-800 font-bold p-4 w-1/2 border-2 border-indigo-800' do
              Register Here

app/views/artists/new.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold uppercase py-12' }
          Add new artist
        %div{ class: 'py-12 flex gap-4' }
          =link_to artists_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            < Go back
      
      = render 'form'
      

app/views/artists/show.html.haml
= render "shared/view"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-50">
    <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <div class="w-full bg-indigo-800 text-white p-4 text-center">
          <%= value %>
        </div>
      <% elsif key == "error" %>
        <div class="w-full bg-red-800 text-white p-4 text-center">
          <%= value %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_view.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-3/4 px-20'}
      %div{ class: 'relative h-2/5 '}
        = image_tag asset_path('default_cover_photo.png'), class: 'h-full w-full object-cover'
        %div{ class: 'rounded-full h-48 w-48 flex items-center justify-center bg-gray-200 p-1 absolute -bottom-24', style: 'left: 42%' }
          = image_tag asset_path('default_avatar.png'), class: 'h-full w-full object-cover rounded-full'
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold uppercase pt-32 pb-12' }
          Albums
        %div{ class: 'pt-32 pb-12 flex gap-4' }
          =link_to artists_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            Artists
          %h1{ class: 'text-gray-400 flex items-center '} /
          =link_to :new_album, class: 'flex items-center text-xl font-bold text-indigo-800' do
            New Album

      - if @albums.empty?
        %h1{ class: 'w-full text-center font-semibold text-4xl text-gray-400 border-t-2 py-10' } No data available

      %div{ class: 'grid grid-cols-5 w-full gap-6' }
        - @albums.each do |album|
          %div{ class: 'border shadow-lg flex flex-col flex items-center' }
            - if album.cover_art.attached?
              = image_tag album.cover_art, class: 'h-48 w-full object-cover album-cover'
            - else
              = image_tag asset_path('album_background.jpg'), class: 'h-48 w-full object-cover album-cover'
            %div{ class: 'p-2 flex flex-col w-full' }
              %h1{ class: 'font-bold text-sm uppercase my-4 text-center' }
                = album.name
              %div{ class: 'flex justify-between w-full text-sm text-gray-700 p-4 bg-gray-100' }
                =link_to tracks_path, class: 'font-bold hover:underline' do
                  Tracks
                =link_to edit_album_path(album.id), class: 'font-bold hover:underline' do
                  Edit
                =link_to album_path(album.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'font-bold hover:underline' do
                  Delete

app/views/tracks/_form.html.haml
= form_with model: @track, class: 'w-full' do |f|
  %div{ class: 'grid grid-cols-2 gap-6 mb-4' }
    %div{ class: 'flex w-full flex-col gap-2 mb-4' }
      %h1 Available?
      %div{ class: 'flex gap-2 items-center h-full w-1/2' }
        %div{ class: 'flex-1' }
          = f.radio_button :available, true
          = f.label :yes
        %div{ class: 'flex-1' }
          = f.radio_button :available, false
          = f.label :no

    %div{ class: 'flex flex-col gap-2' }
      = f.label :url
      = f.file_field :url, accept:'audio/*'
      - if f.object.errors[:url].present?
        %span{ class: 'text-red-500 text-sm' }= f.object.errors[:url].to_sentence
  %div{ class: 'w-full mb-4' }
    = f.text_field :name, class: "#{f.object.errors[:name].present? ? 'border-red-500 border' : 'border-gray-500 border'} p-2 w-full rounded", placeholder: 'Name'
    - if f.object.errors[:name].present?
      %span{ class: 'text-red-500 text-sm' }= f.object.errors[:name].to_sentence

  = f.text_area :credits, class: "#{f.object.errors[:credits].present? ? 'border-red-500 border' : 'border-gray-500 border'} p-2 w-full rounded", rows: 5, placeholder: 'Write something for the credits...'
  - if f.object.errors[:credits].present?
    %span{ class: 'text-red-500 text-sm' }= f.object.errors[:credits].to_sentence

  %div{ class: 'w-full flex justify-end mt-2' }
    = f.submit class: 'px-4 py-2 w-40 bg-indigo-800 text-white hover:bg-indigo-700 cursor-pointer rounded'

app/views/tracks/edit.html.haml
%div{ class: 'bg-white h-screen' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2'}
      %h1{ class: 'text-4xl font-bold uppercase py-12' }
        Track >
        = @track.name
      
      = render 'form'
      

app/views/tracks/index.html.haml
%div{ class: 'bg-white h-screen bg-gray-50' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2 pb-10'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-4xl font-bold uppercase py-12' }
          Tracks
        %div{ class: 'py-12 flex gap-4' }
          =link_to albums_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            Albums
          %h1{ class: 'text-gray-400 flex items-center '} /
          =link_to :new_track, class: 'flex items-center text-xl font-bold text-indigo-800' do
            New Track
      - if @tracks.empty?
        %h1{ class: 'w-full text-center font-semibold text-4xl text-gray-400 border-t-2 py-10' } No data available

      %div{ class: 'flex flex-col w-full gap-6 mt-4' }
        - @tracks.each do |track|
          %div{ class: 'border shadow-lg flex flex-col flex items-center p-2' }
            %div{ class: 'py-4 flex w-full px-4 gap-5' }
              %div{ class: 'w-48 flex-col'}
                = image_tag asset_path('pict--audio-wave-audio-vector-stencils-library.png'), class: 'h-full w-32 w-full object-cover rounded shadow'
              %div{ class: 'flex-1 flex-col justify-between'}
                %h1{ class: 'font-bold text-lg mb-3' }
                  = track.name
                %div
                  %p{ class: 'text-gray-600 mb-4 text-sm' }
                    = track.credits.truncate(100)
                %audio{ :controls => 'controls', class: 'w-full' }
                  %source{ :src => url_for(track.url) }
                %div{ class: 'flex justify-end mt-4' }
                  =link_to edit_track_path(track.id), class: 'font-bold text-indigo-800 hover:underline pt-3 mr-4' do
                    Edit
                  =link_to track_path(track.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'font-bold text-indigo-800 hover:underline pt-3' do
                    Delete

app/views/tracks/new.html.haml
%div{ class: 'bg-white h-screen' }
  %div{ class: 'flex justify-center' }
    %div{ class: 'w-1/2'}
      %div{ class: 'flex justify-between' }
        %h1{ class: 'text-2xl font-bold uppercase py-12' }
          Add new track
        %div{ class: 'py-12 flex gap-4' }
          =link_to tracks_path, class: 'flex items-center text-xl font-bold text-indigo-800' do
            < Go back
      
      = render 'form'
      